# -*- coding: utf-8 -*-
"""stocks_plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOHUR6ZJTSOXrtiuuHFbnjKF3emlGEdD
"""

# Commented out IPython magic to ensure Python compatibility.

# Data source
import yfinance as yf

# Data wrangling
import numpy as np
import pandas as pd

# Data viz
import seaborn as sns
import matplotlib.pyplot as plt
# from plotting import plot_crash_detections, plot_crash_comparisons
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'
sns.set(color_codes=True, rc={'figure.figsize':(12, 4)})
sns.set_palette(sns.color_palette('muted'))

def getstock(stock_name):
  SP500 = yf.Ticker(stock_name)
  sp500_df = SP500.history(period="max")
  return sp500_df
list=["MNST","TSCO","ODFL","RELI","NVDA","NFLX","AMZN","IDXX","ANSS","ISRG","AAPL","RHHBY","MA","DIS","ORCL","LVMUY","KO","INTC","MO","UNH","BABA","BAC","XOM","HD","JPM"]
for i in list:
  sp500_df=getstock(i)
  price_df = sp500_df['Close']
  # price_df.plot()
  # plt.title('Close Price')
  #  plt.show()
  start_year = '2019'
  price_resampled_df = price_df.resample('24H').pad()[start_year:]
  plt.plot(price_resampled_df)
plt.title('Price')
plt.show()



# use pad to replace missing values by last non-missing value

print(sp500_df.head(5))
df1=sp500_df